name: Daily Scraping

on:
  schedule:
    - cron: '1 3 * * *'  # Runs every day at 3:01 AM
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.5'

    - name: Install dependencies
      run: |
        pip install --upgrade numpy pandas
        # Install Python dependencies from requirements.txt
        pip install -r requirements.txt
        # Install selenium, chromedriver-autoinstaller, and pyvirtualdisplay if not already in requirements.txt
        pip install selenium chromedriver-autoinstaller pyvirtualdisplay

    - name: Install xvfb
      run: sudo apt-get install -y xvfb

    - name: Start xvfb and run scraping script
      env:
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
      run: |
        # Start virtual display for headless Chrome
        Xvfb :99 -screen 0 1920x1080x24 &
        export DISPLAY=:99

        # Run the scraping script
        python code/nba.py

    - name: Commit and Push Results
      if: success()
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add -A
        git commit -m "GitHub Actions Results added"
        git push
