name: Daily Scraping

on:
  schedule:
    - cron: '1 3 * * *'  # Runs every day at 3:01 AM
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.5'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        # Ensure selenium and pyvirtualdisplay are installed
        pip install selenium pyvirtualdisplay

    - name: Install xvfb
      run: sudo apt-get install -y xvfb

    - name: Download and install EdgeDriver
      run: |
        # Get the latest EdgeDriver version
        LATEST_DRIVER=$(curl -s https://msedgedriver.azureedge.net/LATEST_STABLE)
        wget -q "https://msedgedriver.azureedge.net/${LATEST_DRIVER}/msedgedriver_linux64.zip" -O msedgedriver.zip
        unzip -q msedgedriver.zip -d /usr/local/bin/
        chmod +x /usr/local/bin/msedgedriver

    - name: Start xvfb and run scraping script
      env:
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
      run: |
        # Start virtual display
        Xvfb :99 -screen 0 1920x1080x24 &
        export DISPLAY=:99

        # Run the scraping script
        python code/nba.py

    - name: Commit and Push Results
      if: success()
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add -A
        git commit -m "GitHub Actions Results added"
        git push
