name: Daily Scraping
on:
  schedule:
    - cron: '1 3 * * *'  # Runs every day at 3:01 AM
  workflow_dispatch:
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.5'
    - name: Removing previous chrome instances on runner
      run: sudo apt purge google-chrome-stable
    - name: Install dependencies
      run: |
        pip uninstall -y numpy pandas
        pip install numpy==1.23.5  # Specify a stable version of numpy
        pip install pandas==1.5.3  # Specify a compatible pandas version
        pip install -r requirements.txt
        pip install selenium chromedriver-autoinstaller pyvirtualdisplay
    - name: Install xvfb
      run: sudo apt-get install -y xvfb
    - name: Start xvfb and run scraping script
      env:
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
      run: |
        Xvfb :99 -screen 0 1920x1080x24 &
        export DISPLAY=:99
        python code/nba.py
    - name: Commit and Push Results
      if: success()
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add -A
        git commit -m "GitHub Actions Results added"
        git push
