name: Daily Script Runner

on:
  schedule:
    - cron: '1 3 * * *'  # Runs daily at 3:01 AM

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Specify the version of Python

    - name: Install dependencies
      run: |
        cd backend  # Change to your backend directory
        pip install -r requirements.txt

    - name: Run the script
      run: |
        cd backend  # Change to your backend directory
        python nba.py
