name: Daily Script Scheduler

on:
  schedule:
    - cron: '1 3 * * *'  # Runs every day at 3:01 AM

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install -r backend/requirements.txt

      - name: Run script
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}  # Access your secret here
        run: |
          python backend/your_script.py
